name: 'my_snowflake_project'
version: '1.0.0'
config-version: 2

profile: 'DBT_Project_Main'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

models:
  my_snowflake_project:
    +materialized: table