DBT_Project_Main:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: '' 
      user: ''    
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DBT_DEMO_DB
      schema: RAW
      threads: 8
    prod:
      type: snowflake
      account: '' # Added this line to keep it consistent with dev
      role: ACCOUNTADMIN
      user: SHIVANGI1.S
      warehouse: COMPUTE_WH
      database: DBT_DEMO_DB
      schema: RAW
      threads: 8