# profiles.yml
default: # This name must match the 'profile:' name in your dbt_project.yml
  outputs:
    dev:
      type: snowflake
      account: '' # Leave as empty string
      user: ''    # Leave as empty string
      role: ACCOUNTADMIN       # e.g., ACCOUNTADMIN or SYSADMIN
      warehouse: COMPUTE_WH    # e.g., COMPUTE_WH
      database: DBT_DEMO_DB     # e.g., ANALYTICS_DB
      schema: RAW   # e.g., DBT_DEV
      threads: 8
  target: dev